### ISSUE TITLE
Noclipping and Teleporting

### ISSUE THREAD

**Issue by DogsGoBark** [overextended/es_extended#22]
**Server Details:**
Windows

**Artifact:**
5056

**Issues:**
I'm not proficient enough with `state bags` to know what's up but it seems like the `if LocalPlayer.state.admin == true` is not shared across from the server?

https://github.com/overextended/es_extended/blob/de17eec73d0c2c121bf60e15723123c014c02dcc/client/main.lua#L246-L267
https://github.com/overextended/es_extended/blob/de17eec73d0c2c121bf60e15723123c014c02dcc/client/main.lua#L269-L302

When attempting to use these commands, nothing happens.

**Comment by thelindat** [comment]
These work fine from testing, aka can't reproduce.

**Comment by benzon** [comment]
I can reproduce the issue.

The issue is `LocalPlayer.state.admin`

So if you got different groups then just admin, and you dont use the following in your cfg it wont work.

`add_ace group.admin command allow`

So even if you change the command to allow lets say mod's access to the command it would not work, RegisterCommand would not fail, but the local state check would fail, since they are not allowed access to command.

The function doing the permission check is the following.

```
Core.IsPlayerAdmin = function(playerId)
	return (IsPlayerAceAllowed(playerId, 'command') or GetConvar('sv_lan', '') == 'true') and true or false
end
```

**Comment by thelindat** [comment]
Not really an issue - the check is where the person has ace permission to use commands and not if they're in a specific group. group.admin may have access to all commands, or their specific identifier.

**Comment by DogsGoBark** [comment]
With all due respect, not sure what's wrong even when I added; `add_ace group.superadmin command allow` to my config I cannot use the `/noclip` or `/tpm` command? Could you provide me an example of the ace permissions  you have @benzon or @thelindat?
